<?xml version="1.0"?>
<package format="2">
  <name>fs150_description</name>
  <version>0.1.0</version>
  <description>Visual description assets for the XGC2 FS150 iris-derived airframe.</description>

  <maintainer email="lxk@xiaokang.local">lxk</maintainer>
  <license>Proprietary</license>

  <buildtool_depend>catkin</buildtool_depend>

  <exec_depend>urdf</exec_depend>

  <export/>
</package>
